In [1]:
import numpy as np

In [3]:
array = np.arange(0,15)

In [4]:
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
array=np.ones((1,5))

In [6]:
print(array)

[[1. 1. 1. 1. 1.]]


In [ ]:
liste1=[0,1,2,4,6,78]
for sonuc in liste1:
    print(sonuc)

: 

In [10]:
x= input("x'i gir: ")
q= input("q'yu gir: ")

sonuc=x+q

print(sonuc)

x'i gir: 15
q'yu gir: 65
1565


In [11]:
benimListem=np.linspace(0,15,30)

In [12]:
benimListem

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

In [13]:
def toplama(num1,num2):
    sum=num1+num2
    print(sum)

In [14]:
toplama(10,25)

35


In [15]:
def keyWordKontrolu(**kwargs):
    if "mehmet" in kwargs:
        print("mehmet var")
    else:
        print("mehmet yok")

In [16]:
keyWordKontrolu(ahmet = 70, zeynep = 50, mehmet = 40)

mehmet var
